apiVersion: v1
kind: Service
metadata:
  name: blockreceiver
  namespace: dev
  labels:
    name: "block-rec-svc"
spec:
  selector:
    app: blockreceiver
  ports:
  - name: block-receiver
    protocol: TCP
    port: 30031
    targetPort: 30031